apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprojecthreadingclouds
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector: 
    matchLabels:
      app:  test
  template:
    metadata:
      labels:
        app:  test
    spec:
      containers:
      - image: eloycd/myprojecthreadingclouds:v1.0.0
        name:  myprojecthreadingclouds
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: myprojecthreadingclouds
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test