apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myprojecthreadingclouds
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector: 
    matchLabels:
      app:  test
  template:
    metadata:
      labels:
        app:  test
    spec:
    
      containers: 
      - image: eloycd/myimagesthreadingclouds:a9ebeb73713613f68f6d2f9e24b944959bfed273
        imagePullPolicy: Always
        name:  myprojecthreadingclouds
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: myprojecthreadingclouds
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: test