apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myprojecthreadingclouds
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector: 
    matchLabels:
      app:  test
  template:
    metadata:
      labels:
        app:  test
    spec:
    
      containers: 
      - image: eloycd/myimagesthreadingclouds:e0f538134569887649e6cd7fd5aad2f14e90950b
        imagePullPolicy: Always
        name:  myprojecthreadingclouds
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: myprojecthreadingclouds
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: test